title: María del Refugio Noriega Vargas
logo: /foto_cv.jpeg
description: In this page I show you some of my projects, you can access the repositories by clicking on the links.
show_donwloads: True
theme: jekyll-theme-minimal
